
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeMinGWFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "mingw32-make.exe"
    candidate_directories:
      - "C:/Users/Trisha Dreyer/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "C:/Users/Trisha Dreyer/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/"
      - "C:/Program Files/Python314/Scripts/"
      - "C:/Program Files/Python314/"
      - "C:/Program Files (x86)/Eclipse Adoptium/jre-8.0.402.6-hotspot/bin/"
      - "C:/Program Files/Eclipse Adoptium/jre-8.0.402.6-hotspot/bin/"
      - "C:/Program Files/Eclipse Adoptium/jre-17.0.10.7-hotspot/bin/"
      - "C:/Program Files/Eclipse Adoptium/jre-11.0.22.7-hotspot/bin/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files/dotnet/"
      - "C:/Program Files (x86)/dotnet/"
      - "C:/Program Files/HP/HP One Agent/"
      - "D:/Git/cmd/"
      - "C:/Program Files/nodejs/"
      - "C:/Users/Trisha Dreyer/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/Trisha Dreyer/AppData/Local/GitHubDesktop/bin/"
      - "C:/Users/Trisha Dreyer/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/Users/Trisha Dreyer/AppData/Roaming/npm/"
      - "C:/Program Files/CMake/bin/"
      - "C:/msys64/mingw64/bin/"
      - "/REGISTRY-NOTFOUND/bin/"
      - "c:/MinGW/bin/"
      - "/MinGW/bin/"
      - "/REGISTRY-NOTFOUND/MinGW/bin/"
    searched_directories:
      - "C:/Users/Trisha Dreyer/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/mingw32-make.exe.com"
      - "C:/Users/Trisha Dreyer/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/mingw32-make.exe"
      - "C:/Users/Trisha Dreyer/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/mingw32-make.exe.com"
      - "C:/Users/Trisha Dreyer/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/mingw32-make.exe"
      - "C:/Program Files/Python314/Scripts/mingw32-make.exe.com"
      - "C:/Program Files/Python314/Scripts/mingw32-make.exe"
      - "C:/Program Files/Python314/mingw32-make.exe.com"
      - "C:/Program Files/Python314/mingw32-make.exe"
      - "C:/Program Files (x86)/Eclipse Adoptium/jre-8.0.402.6-hotspot/bin/mingw32-make.exe.com"
      - "C:/Program Files (x86)/Eclipse Adoptium/jre-8.0.402.6-hotspot/bin/mingw32-make.exe"
      - "C:/Program Files/Eclipse Adoptium/jre-8.0.402.6-hotspot/bin/mingw32-make.exe.com"
      - "C:/Program Files/Eclipse Adoptium/jre-8.0.402.6-hotspot/bin/mingw32-make.exe"
      - "C:/Program Files/Eclipse Adoptium/jre-17.0.10.7-hotspot/bin/mingw32-make.exe.com"
      - "C:/Program Files/Eclipse Adoptium/jre-17.0.10.7-hotspot/bin/mingw32-make.exe"
      - "C:/Program Files/Eclipse Adoptium/jre-11.0.22.7-hotspot/bin/mingw32-make.exe.com"
      - "C:/Program Files/Eclipse Adoptium/jre-11.0.22.7-hotspot/bin/mingw32-make.exe"
      - "C:/Windows/System32/mingw32-make.exe.com"
      - "C:/Windows/System32/mingw32-make.exe"
      - "C:/Windows/mingw32-make.exe.com"
      - "C:/Windows/mingw32-make.exe"
      - "C:/Windows/System32/wbem/mingw32-make.exe.com"
      - "C:/Windows/System32/wbem/mingw32-make.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe.com"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe"
      - "C:/Program Files/dotnet/mingw32-make.exe.com"
      - "C:/Program Files/dotnet/mingw32-make.exe"
      - "C:/Program Files (x86)/dotnet/mingw32-make.exe.com"
      - "C:/Program Files (x86)/dotnet/mingw32-make.exe"
      - "C:/Program Files/HP/HP One Agent/mingw32-make.exe.com"
      - "C:/Program Files/HP/HP One Agent/mingw32-make.exe"
      - "D:/Git/cmd/mingw32-make.exe.com"
      - "D:/Git/cmd/mingw32-make.exe"
      - "C:/Program Files/nodejs/mingw32-make.exe.com"
      - "C:/Program Files/nodejs/mingw32-make.exe"
      - "C:/Users/Trisha Dreyer/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe.com"
      - "C:/Users/Trisha Dreyer/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe"
      - "C:/Users/Trisha Dreyer/AppData/Local/GitHubDesktop/bin/mingw32-make.exe.com"
      - "C:/Users/Trisha Dreyer/AppData/Local/GitHubDesktop/bin/mingw32-make.exe"
      - "C:/Users/Trisha Dreyer/AppData/Local/Programs/Microsoft VS Code/bin/mingw32-make.exe.com"
      - "C:/Users/Trisha Dreyer/AppData/Local/Programs/Microsoft VS Code/bin/mingw32-make.exe"
      - "C:/Users/Trisha Dreyer/AppData/Roaming/npm/mingw32-make.exe.com"
      - "C:/Users/Trisha Dreyer/AppData/Roaming/npm/mingw32-make.exe"
      - "C:/Program Files/CMake/bin/mingw32-make.exe.com"
      - "C:/Program Files/CMake/bin/mingw32-make.exe"
      - "C:/msys64/mingw64/bin/mingw32-make.exe.com"
      - "C:/msys64/mingw64/bin/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe"
      - "c:/MinGW/bin/mingw32-make.exe.com"
      - "c:/MinGW/bin/mingw32-make.exe"
      - "/MinGW/bin/mingw32-make.exe.com"
      - "/MinGW/bin/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe"
    found: false
    search_context:
      ENV{PATH}:
        - "c:\\Users\\Trisha Dreyer\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\debugCommand"
        - "c:\\Users\\Trisha Dreyer\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\copilotCli"
        - "C:\\Program Files\\Python314\\Scripts\\"
        - "C:\\Program Files\\Python314\\"
        - "C:\\Program Files (x86)\\Eclipse Adoptium\\jre-8.0.402.6-hotspot\\bin"
        - "C:\\Program Files\\Eclipse Adoptium\\jre-8.0.402.6-hotspot\\bin"
        - "C:\\Program Files\\Eclipse Adoptium\\jre-17.0.10.7-hotspot\\bin"
        - "C:\\Program Files\\Eclipse Adoptium\\jre-11.0.22.7-hotspot\\bin"
        - "C:\\windows\\system32"
        - "C:\\windows"
        - "C:\\windows\\System32\\Wbem"
        - "C:\\windows\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\windows\\System32\\OpenSSH\\"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files (x86)\\dotnet\\"
        - "C:\\Program Files\\HP\\HP One Agent"
        - "D:\\Git\\cmd"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\Users\\Trisha Dreyer\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\Trisha Dreyer\\AppData\\Local\\GitHubDesktop\\bin"
        - "C:\\Users\\Trisha Dreyer\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Users\\Trisha Dreyer\\AppData\\Roaming\\npm"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\msys64\\mingw64\\bin"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\msys64\\mingw64\\bin"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\msys64\\mingw64\\bin"
...
